version: '3.2'
services:

  nginx:
    image: nginx:1.13.8
    command: nginx -g 'daemon off;' -c /etc/nginx/nginx.conf
    ports:
      - 8000:80
    volumes:
      - ./docker/docker-compose/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/docker-compose/config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./public:/usr/share/nginx/html
    depends_on:
      - neverblock

  neverblock:
    entrypoint: tini -g -- docker/entrypoint/neverblock.sh
    command: /usr/local/sbin/php-fpm
    build:
      context: .
      dockerfile: docker/images/neverblock/Dockerfile
    restart: unless-stopped
    volumes:
      - ./neverblock:/opt/app/public


